### ISSUE TITLE
lsp-javascript-typescript has exited (exited abnormally with code 1)

### ISSUE THREAD

**Issue by shackra** [emacs-lsp/lsp-javascript#27]
Installed the package yesterday and did the configuration on my machine, however it does not work out of the box. This is the output I get after setting `lsp-print-io` to `non-nil` and opening a JS file:

```
lsp--stdio-wait: Content-Length: 1377

{
  "jsonrpc": "2.0",
  "method": "initialize",
  "params": {
    "processId": 12675,
    "rootPath": "/home/jorge/proyectos/mtg-bread/",
    "rootUri": "file:///home/jorge/proyectos/mtg-bread/",
    "capabilities": {
      "workspace": {
        "applyEdit": true,
        "executeCommand": {
          "dynamicRegistration": true
        }
      },
      "textDocument": {
        "synchronization": {
          "willSave": true,
          "didSave": true,
          "willSaveWaitUntil": true
        },
        "symbol": {
          "symbolKind": {
            "valueSet": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23,
              24,
              25
            ]
          }
        },
        "formatting": {
          "dynamicRegistration": true
        },
        "codeAction": {
          "dynamicRegistration": true
        },
        "completion": {
          "completionItem": {
            "snippetSupport": true
          }
        }
      }
    },
    "initializationOptions": null
  },
  "id": 1
}
/home/jorge/proyectos/mtg-bread/: lsp-javascript-typescript has exited (exited abnormally with code 1)
File mode specification error: (lsp-timed-out-error)
lsp--send-no-wait: Content-Length: 238

{
  "jsonrpc": "2.0",
  "method": "textDocument/hover",
  "params": {
    "textDocument": {
      "uri": "file:///home/jorge/proyectos/mtg-bread/App.js"
    },
    "position": {
      "line": 0,
      "character": 0
    }
  },
  "id": 2
}
Error in post-command-hook (lsp-ui-doc--make-request): (error "lsp-javascript-typescript: Cannot communicate with the process (exit)")
```
This is what I got from a buffer called `*lsp-javascript-typescript stderr*` several times, each with a different package missing after installing the last one reported: 
```
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'fast-json-patch'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/lib/node_modules/javascript-typescript-langserver/lib/connection.js:12:27)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

Process lsp-javascript-typescript stderr finished
```
This is how I install the NodeJS stuff:
```
npm install -g babel-cli babel-preset-react eslint@3.x babel-eslint@7 eslint-plugin-react typescript-language-server javascript-typescript-langserver
```
And, this is my current configuration in Emacs:
```
(setq-default js-indent-level 2)

(use-package ng2-mode)
(use-package typescript-mode
  :init (setf typescript-indent-level js-indent-level)
  :config
  (with-eval-after-load "lsp-javascript-typescript"
    (add-hook 'typescript-mode-hook #'lsp-javascript-typescript-enable)))

(use-package lsp-javascript-typescript)

(use-package js2-refactor
  :after (js2-mode)
  :config
  (add-hook 'js2-mode-hook #'js2-refactor-mode)
  (js2r-add-keybindings-with-prefix "C-c C-m"))

(use-package xref-js2
  :after (js2-mode)
  :init
  (add-hook 'js2-mode-hook (lambda () (add-hook 'xref-backend-functions #'xref-js2-xref-backend nil t))))

(use-package js2-mode
  :mode "\\.js\\'"
  :init
  (add-hook 'js2-mode-hook #'js2-imenu-extras-mode)
  :config
  (with-eval-after-load "lsp-javascript-typescript"
    (add-hook 'js2-mode-hook #'lsp-javascript-typescript-enable)))

;; Indium se conecta con una pestaña del navegador web o un proceso de NodeJS
;; y provee varias características para el desarrollo en JavaScript
(use-package indium ;; https://indium.readthedocs.io/en/latest/setup.html
  :config
  (add-hook 'js-mode-hook #'indium-interaction-mode))

;; Modo mayor para trabajar con Reactive.JS
(use-package rjsx-mode
  :init
  (add-to-list 'auto-mode-alist '("components?\\/.*\\.js\\'" . rjsx-mode))
  (add-to-list 'auto-mode-alist '("containers?\\/.*\\.js\\'" . rjsx-mode))
  (add-hook 'rjsx-mode-hook (lambda () (flyspell-mode-off)))
  :config
  ;; tomado de https://emacs.stackexchange.com/a/33544/690 mejora el sangrado
  ;; de lineas
  (defadvice js-jsx-indent-line (after js-jsx-indent-line-after-hack activate)
    "Workaround sgml-mode and follow airbnb component style."
    (save-excursion
      (beginning-of-line)
      (if (looking-at-p "^ +\/?> *$")
          (delete-char sgml-basic-offset))))
  (with-eval-after-load "lsp-javascript-typescript"
    (add-hook 'rjsx-mode-hook #'lsp-javascript-typescript-enable)))

(with-eval-after-load flycheck-mode
  ;; tomado de https://jamiecollinson.com/blog/my-emacs-config/ hace que
  ;; flycheck utilice eslint instalado en el proyecto en lugar del habilitado
  ;; globalmente en el sistema
  (defun jc/use-eslint-from-node-modules ()
    "Set local eslint if available."
    (let* ((root (locate-dominating-file
                  (or (buffer-file-name) default-directory)
                  "node_modules"))
           (eslint (and root
                        (expand-file-name "node_modules/eslint/bin/eslint.js"
                                          root))))
      (when (and eslint (file-executable-p eslint))
        (setq-local flycheck-javascript-eslint-executable eslint))))

  (add-hook 'flycheck-mode-hook #'jc/use-eslint-from-node-module))
```

**Comment by shackra** [comment]
Okay, this was confusing.

I decided to remove the package all together:

```
sudo npm remove -g javascript-typescript-langserver
```
And turns out I had `javascript-typescript-stdio` installed anyway in my system:

```
whereis javascript-typescript-stdio
javascript-typescript-stdio: /usr/local/bin/javascript-typescript-stdio
```

And now `lsp-javascript-typescript` works out of the box.

This installation process is confusing because I dont really know from where the binary `/usr/local/bin/javascript-typescript-stdio` comes from (removing `typescript-language-server` and `javascript-typescript-langserver` does nothing).
